
# Site settings
# Update url/baseurl after enabling Pages.

name: "META-Sig: Microbiome Metabolite Signatures"
title: "META-Sig: Microbiome Metabolite Signatures"
description: "Documentation website for META-Sig — a pipeline to attribute metabolites to microbial origin and derive robust microbial metabolite signatures."

# Theme
remote_theme: "just-the-docs/just-the-docs"
color_scheme: "light"
favicon_ico: "/assets/favicon.ico"

# Footer links
aux_links:
  "GitHub Repository":
    - "https://github.com/RuiF-GitHub/META-Sig-Microbiome-Metabolite-Signatures"

# Search
search_enabled: true

just_the_docs:
  callouts:
    note:
      title: "Note"
      color: "blue"
    warning:
      title: "Warning"
      color: "red"
    tip:
      title: "Tip"
      color: "green"

markdown: "kramdown"
kramdown:
  input: GFM
  hard_wrap: false
